spring:
  application:
    name: wlb-ledger-engine

  datasource:
    # ? ???? 1?????? (?????? 3306 Port ? chronicle_wlb_db ???)
    url: jdbc:mysql://localhost:3306/chronicle_wlb_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei

    # ? ???? 2???????? (AppServ ????? root)
    username: root

    # ? ???? 3???????? (AppServ ?????????????????????)
    password: ${DB_PASSWORD:1234}

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # ? IntelliJ ?????? SQL ??????????????????
    show-sql: true
    hibernate:
      # validate ?????????? Java ?? Entity ???? MySQL ? 7 ????
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true