# ===============================
# MySQL ??????
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/chronicle_wlb_db?serverTimezone=Asia/Taipei&characterEncoding=utf-8
# ?????? MySQL ??????????? root
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Hibernate / JPA (ORM ????)
# ===============================
# ?????? Spring Boot ?????? SQL ?? (??????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ? ?????????ddl-auto
# ?????????? schema.sql ?? 7 ??????????? validate
# validate ?????Spring ?????????Java Entity ? MySQL ????? 100% ????????????
spring.jpa.hibernate.ddl-auto=validate